ALTER TABLE "Order" ADD COLUMN "zipCode" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN "street" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN "addressNumber" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN "neighborhood" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN "city" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN "stateCode" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN "complement" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN "referencePoint" TEXT NOT NULL DEFAULT '';
